name: Unity Package Release

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
        description: "The name of the package to be released"
      create-unity-package:
        required: false
        type: boolean
        default: true
        description: "Whether to create .unitypackage file"
      create-zip:
        required: false
        type: boolean
        default: true
        description: "Whether to create zip file"
      version-file:
        required: false
        type: string
        default: "package.json"
        description: "File to read version from"
      changelog-file:
        required: false
        type: string
        default: "CHANGELOG.md"
        description: "Path to changelog file"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录用于生成changelog

      - name: Get Version
        id: version
        run: |
          echo "version=$(jq -r .version ${{ inputs.version-file }})" >> $GITHUB_OUTPUT
    
      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ inputs.package-name }}-${{ steps.version.outputs.version }}.zip" >> $GITHUB_ENV
          echo "unityPackage=${{ inputs.package-name }}-${{ steps.version.outputs.version }}.unitypackage" >> $GITHUB_ENV

      - name: Create Package Zip
        if: inputs.create-zip
        run: zip -r "${{ github.workspace }}/${{ env.zipFile }}" .
      
      - name: Track Package Meta Files
        if: inputs.create-unity-package
        run: find . -name \*.meta >> metaList
      
      - name: Create UnityPackage
        if: inputs.create-unity-package
        uses: pCYSl5EDgo/create-unitypackage@v1.2.3
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList

      - name: Get Changelog Entry
        id: changelog_reader
        continue-on-error: true
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.version.outputs.version }}
          path: ${{ inputs.changelog-file }}

      - name: Set Default Changelog
        if: steps.changelog_reader.outcome == 'failure'
        id: default_changelog
        run: |
          echo "changes=Release version ${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Prepare Release Files
        id: prepare_files
        run: |
          files=()
          [[ "${{ inputs.create-zip }}" == "true" ]] && files+=("${{ env.zipFile }}")
          [[ "${{ inputs.create-unity-package }}" == "true" ]] && files+=("${{ env.unityPackage }}")
          files+=("${{ inputs.version-file }}")
          echo "files=${files[*]}" >> $GITHUB_OUTPUT

      - name: Make Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog_reader.outcome == 'success' && steps.changelog_reader.outputs.changes || steps.default_changelog.outputs.changes }}
          files: ${{ steps.prepare_files.outputs.files }}
          tag_name: ${{ steps.version.outputs.version }} 